### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Thepowa753** [ch3p4ll3/binanceban#2]
Is this still working? I think you need to update

**Comment by Thepowa753** [comment]
![T00453IR](https://github.com/ch3p4ll3/binanceban/assets/44495483/bf12f759-b63e-498a-8874-2e3892a73648)
Take this billet!

**Comment by ch3p4ll3** [comment]
LMAO no, don't care anymore about this repo. Also, IDK what is a "billet". Bruh never heard of it. Seems kinda hot btw

**Comment by Thepowa753** [comment]
you crazy lil girl
